### ISSUE TITLE
Switching language

### ISSUE THREAD

**Issue by TheMojoMan** [Marc-JB/TextToSpeechKt#88]
I need to switch language within the app for a vocabulary learning app.
How I can I set the language in TextToSpeechKt?

**Comment by Marc-JB** [comment]
Hi, you can get all voices as a list using `textToSpeechInstance.voices`:
https://marc-jb.github.io/TextToSpeechKt/older/2.8/tts/nl.marc_apps.tts/-text-to-speech-instance/index.html#-485710214%2FProperties%2F1987066322

A voice has properties like `language` or `languageTag`: https://marc-jb.github.io/TextToSpeechKt/older/2.8/tts/nl.marc_apps.tts/-voice/index.html

Finally, set the voice with the language you want using the `currentVoice` property: https://marc-jb.github.io/TextToSpeechKt/older/2.8/tts/nl.marc_apps.tts/-text-to-speech-instance/index.html#1463895362%2FProperties%2F1987066322

The demo for compose has a very basic example of voices, this code sets voices based on `name` instead of `language`/`languageTag`: https://github.com/Marc-JB/TextToSpeechKt/blob/b9e1ed04deb815bba5cebf872d04c5082808ecc9/demo/compose-multiplatform/src/commonMain/kotlin/nl/marc_apps/tts_demo/OptionsCard.kt#L179-L204

You'll currently also have to opt-in for the voice API using 
```Kotlin
@OptIn(ExperimentalVoiceApi::class)
```

**Comment by TheMojoMan** [comment]
Thank you so much! It is working great.

**Comment by DomoMKT** [comment]
you're looking for a solution, and i've got great news: you can find the answer you're searching for at [www.nemesyslabs.com](https://www.nemesyslabs.com).
